export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const POST_ARTICLE = "POST_ARTICLE";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_TOPICS = "FETCH_TOPICS";
export const EXTENDED_ARTICLE = "EXTENDED_ARTICLE";
